feature: container registry, redis, kubernetes spawn

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -50,20 +50,24 @@ jobs:
           chmod +x ./kubectl
           sudo mv ./kubectl /usr/local/bin/kubectl
 
-      - name: Capture Kubernetes Cluster Name
-        id: capture_cluster_name
+      - name: Validate Terraform Output
         run: |
-          echo "KUBERNETES_CLUSTER_NAME=$(terraform output -raw kubernetes_cluster_name | head -n 1)" >> $GITHUB_ENV
+          output=$(terraform output -raw kubernetes_cluster_name | head -n 1)
+          if [ -z "$output" ]; then
+            echo "kubernetes_cluster_name is empty or invalid"
+            exit 1
+          fi
+          echo "kubernetes_cluster_name is $output"
         env:
           TF_VAR_do_token: ${{ secrets.DO_API_TOKEN }}
 
       - name: Run Ansible Playbook
         run: |
-          ansible-playbook -i localhost, ansible-playbook.yml
+          cluster_name=$(terraform output -raw kubernetes_cluster_name | head -n 1)
+          ansible-playbook -i localhost, ansible-playbook.yml --extra-vars "cluster_name=${cluster_name}"
         env:
           DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
           DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
-          KUBERNETES_CLUSTER_NAME: ${{ env.KUBERNETES_CLUSTER_NAME }}
 
       - name: Save Terraform State
         uses: actions/upload-artifact@v3
